### ISSUE TITLE
[BUGS] Cannot Move to Previous Page After Clicking The Button Called "Share Your Love"

### ISSUE THREAD

**Issue by codewithrabeeh** [IAmTamal/Milan#547] opened 2022-11-08 11:48 UTC
### Description

After clicking the (Share Your Love) button on the home page, we can't move to the previous page. Also the "Please log in before donating" alert is frequently coming when clicking the back button.

### Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/65481473/200555364-5647917c-24c0-44b5-8b07-97638830580a.gif)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment] 2022-11-15 07:12
Hmm this does seems like a bug, would you consider fixing it  ?

**Comment by codewithrabeeh** [comment] 2022-11-15 11:20
> I can fix this bug if it is still open.

Go ahead! @IAmTamal let him do this!

**Comment by imvedanshmehra** [comment] 2022-11-15 19:09
Thank you for assigning this issue. What is the expected behavior here?

**Comment by IAmTamal** [comment] 2022-11-16 04:25
> Thank you for assigning this issue. What is the expected behavior here?

Hello there , 

Currently if you click on the  `You can help us too !!` section without logging in as a user, it will take you to the user's login page and a toast will appear to the right about logging in first. 

These are okay, but now if i want to go to home page i'll still be on the same page with the warnings again and again. 

The reason for this is we are checking authentication on the `/donateus` page and on trying to go back from `/user/login` with the browser's back button we are landing again and again on the `/donateus` page thus the loop. 


## A possible solution 

- A possible solution might be transferring the authentication check from the `/donateus` page to the `Share your love` button. 
- That might stop the loop from happening !

**Comment by imvedanshmehra** [comment] 2022-11-16 08:13
I have raised a PR with the fix. 

We should also consider adding `protected routes` which will check if the user is logged in or not and based on that it will either redirect them to the page that they are trying to access or else it will redirect them to the login page.

**Comment by IAmTamal** [comment] 2022-12-03 13:56
> I have raised a PR with the fix.
> 
> We should also consider adding `protected routes` which will check if the user is logged in or not and based on that it will either redirect them to the page that they are trying to access or else it will redirect them to the login page.

Yes we can add protected routes too, however i want the users to know that they need to log in first and also send a toast message !

**Closed** 2022-12-03 13:59 UTC
Labels: 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, 🛠 status : under development
